# Generated by Django 4.1.2 on 2022-10-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paperType', models.CharField(choices=[('0', 'ژورنال داخلی'), ('1', 'ژورنال خارجی'), ('2', 'کنفرانس داخلی'), ('3', 'کنفرانس خارجی')], max_length=1)),
                ('title', models.CharField(max_length=500)),
                ('doi', models.CharField(max_length=1000)),
                ('author1', models.CharField(max_length=500)),
                ('author2', models.CharField(max_length=500)),
                ('author3', models.CharField(max_length=500)),
                ('author4', models.CharField(max_length=500)),
                ('abstract', models.TextField()),
                ('journal', models.CharField(max_length=500)),
                ('issn', models.CharField(max_length=500)),
                ('volume', models.CharField(max_length=500)),
                ('publication_date', models.DateField()),
                ('rank', models.CharField(max_length=500)),
            ],
        ),
    ]
