# Generated by Django 4.1.2 on 2022-11-05 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researchActivities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confTopic', models.CharField(choices=[('0', 'مهندسی و علوم فیزیکی'), ('1', 'کشاورزی و علوم زیستی'), ('2', 'پزشکی'), ('3', 'علوم انسانی')], max_length=1, verbose_name='موضوع کنفرانس')),
                ('confType', models.CharField(choices=[('0', 'منطقه ای'), ('1', 'ملی'), ('2', 'بین المللی')], max_length=500, verbose_name='نوع کنفرانس')),
                ('title', models.CharField(max_length=500, verbose_name='عنوان کنفرانس')),
                ('event_date', models.DateField(verbose_name='تاریخ برگزاری')),
                ('event_place', models.CharField(max_length=500, verbose_name='محل برگزاری')),
            ],
            options={
                'verbose_name': 'کنفرانس',
                'verbose_name_plural': 'کنفرانس ها',
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journalType', models.CharField(choices=[('0', 'داخلی'), ('1', 'خارجی')], max_length=1, verbose_name='نوع ژورنال')),
                ('title', models.CharField(max_length=500, verbose_name='عنوان ژورنال')),
                ('issn', models.CharField(max_length=500, verbose_name='شابک')),
                ('volume', models.CharField(max_length=500, verbose_name='شمارگان ژورنال')),
                ('publisher', models.DateField(verbose_name='ناشر')),
                ('rank', models.CharField(max_length=500, verbose_name='رتبه ژورنال')),
            ],
            options={
                'verbose_name': 'ژورنال',
                'verbose_name_plural': 'ژورنال ها',
            },
        ),
        migrations.AlterModelOptions(
            name='paper',
            options={'verbose_name': 'مقاله', 'verbose_name_plural': 'مقاله ها'},
        ),
        migrations.AlterField(
            model_name='paper',
            name='abstract',
            field=models.TextField(verbose_name='چکیده مقاله'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='author1',
            field=models.CharField(max_length=500, verbose_name='نویسنده اول'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='author2',
            field=models.CharField(max_length=500, verbose_name='نویسنده دوم'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='author3',
            field=models.CharField(max_length=500, verbose_name='نویسنده سوم'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='author4',
            field=models.CharField(max_length=500, verbose_name='نویسنده چهارم'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='issn',
            field=models.CharField(max_length=500, verbose_name='شابک'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='paperType',
            field=models.CharField(choices=[('0', 'ژورنال داخلی'), ('1', 'ژورنال خارجی'), ('2', 'کنفرانس داخلی'), ('3', 'کنفرانس خارجی')], max_length=1, verbose_name='نوع مقاله'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='publication_date',
            field=models.DateField(verbose_name='تاریخ انتشار'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='rank',
            field=models.CharField(max_length=500, verbose_name='رتبه ژورنال'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(max_length=500, verbose_name='عنوان مقاله'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='volume',
            field=models.CharField(max_length=500, verbose_name='شمارگان ژورنال'),
        ),
        migrations.AddField(
            model_name='paper',
            name='conference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='researchActivities.conference', verbose_name='کنفرانس'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='researchActivities.journal', verbose_name='ژورنال'),
        ),
    ]
