# Generated by Django 4.1.2 on 2022-11-12 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researchActivities', '0002_conference_journal_alter_paper_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='rank',
        ),
    ]
